### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/market-maker-tools#25]
List of required features for arby release from my side:

features:
+  [ ] cancel XUD orders on graceful shutdown and for ANY unexpected situation if it is possible
+  [x] arby using with real binance creds and orders
+  [x] add details to binance order placing and filling instead of TODO 

bugs:
+ [x] channel checking (dont place order till no 2 active channels)
+ [x] understand tradinglimits (if I sold 5 ETH/BTC, qty of buy order should be increased)
+ [x] there is no binance order sending in logs for simnet network with arby order is filled (tested with not last commit)

+ handle significant price moves (not sure that it is required for release, but it would be good) 
 **is removed from required features list after the meeting;**

Feel free to add something else and comment.

**Comment by erkarl** [comment]
> arby should be controllable (at least stoptrade/starttrade command and do not start trade automatically after container creation)

At the moment you can do `stop arby` and `start arby` within the docker CLI. Is that not sufficient?

> cancel XUD orders on graceful shutdown and for ANY unexpected situation if it is possible
Yep, this has been on my internal TODO list for a while. 

https://github.com/ExchangeUnion/market-maker-tools/issues/27

> arby using with real binance creds and orders

https://github.com/ExchangeUnion/market-maker-tools/issues/28

> channel checking (dont place order till no 2 active channels)

I don't understand what you mean here. Can you elaborate?

> understand tradinglimits (if I sold 5 ETH/BTC, qty of buy order should be increased)

I believe issues with order quantities were addressed with https://github.com/ExchangeUnion/market-maker-tools/pull/22

> there is no binance order sending in logs for simnet network with arby order is filled (tested with not last commit)

Should be working with latest version.

**Comment by kilrau** [comment]
> At the moment you can do stop arby and start arby within the docker CLI. Is that not sufficient?

I think it is. Just need to add it to the docs and that's it. Anybody taking care of the docs (https://docs.exchangeunion.com/start-earning/market-maker-guide#connect-to-exchange-for-market-makers) or shall I?

> I don't understand what you mean here. Can you elaborate?

Should also be closed by https://github.com/ExchangeUnion/market-maker-tools/pull/22

**Comment by raladev** [comment]
> > I don't understand what you mean here. Can you elaborate?
> 
> Should also be closed by #22

Yeap it closed by #22. Marked as done.
channel checking (dont place order till no 2 active channels) and there is no binance order sending in logs for simnet network with arby order is filled (tested with not last commit) are marked as done too.

**Comment by raladev** [comment]
> > At the moment you can do stop arby and start arby within the docker CLI. Is that not sufficient?
> 
> I think it is. Just need to add it to the docs and that's it. Anybody taking care of the docs (https://docs.exchangeunion.com/start-earning/market-maker-guide#connect-to-exchange-for-market-makers) or shall I?
I dont think so, in current situation we have auto-started and used by default container that starts to place orders when see opened channels using full available balance of channel. Its defiantly not save behavior for me and my money. 
At least it should be configurable - start trade immediately or just pull the image and create container for start in the future when i will be ready for that.

**Comment by kilrau** [comment]
I get your point and it's good feedback. I just want to avoid making it too complicated to get arby up and running and especially avoid complications during operation. By default we assume everyone is market maker and everyone would want to run arby. So asking for a permission / require manual start when bringing up the environment is somewhat complicated since it would also apply in cases where e.g. arby is updated.

Currently it requires the following for arby to start issuing orders:
- xud-docker with all clients up and synced
- at least two assets with channelbalance and these configured as pair
- binance/CEX api keys manually configured in conf with minimum the same two assets having balance

What I would **not** want to do:
- require another `start arby` command when all of the above requirements are fullfilled every time the requirement is restarted/updated etc. That will annoy very quickly.

Comparing it somewhat to LNDs autopilot which we noticed is on by default now too, what we could do is:
- [ ] add an arby.active option which defaults to true but allows anyone to switch off arby via conf/cli parameter (without deleting the rest of the arby options from the config)
- [ ] add arby to the xud getinfo call to bring to the users awareness when arby is up and issuing orders, maybe displaying order amounts
- [ ] display a super short list of arby commands (atm `arby stop`, `arby start`) when the user types `arby` in xud ctl
- [ ] not sure about this one: require a one-time confirmation when starting arby for the first time: `Arby was configured successfully and will automatically start issuing orders using your available balances. Read more about how arby works at exchangeunion.com/arby. Do you want to proceed? [Y/n]`

Let me know which of the above you consider meaningful. @raladev @erkarl

**Comment by erkarl** [comment]
> add an arby.active option which defaults to true but allows anyone to switch off arby via conf/cli parameter (without deleting the rest of the arby options from the config)

Isn't this already implemented via `arby.disabled=false` in network.conf?

**Comment by kilrau** [comment]
> Isn't this already implemented via `arby.disabled=false` in network.conf?

... you are right. Removed this point.

**Comment by raladev** [comment]
> Let me know which of the above you consider meaningful. @raladev @erkarl

Agreed with all three points, they will make use of arbi more visible.

If you are not sure about third, then just mention about arby running and orders issuing may be enough (without the question).

> binance/CEX api keys manually configured in conf with minimum the same two assets having balance

I dont understand why I should have balance for 2 assets on binance.
One asset should be enough to trade by one side (only buy orders for example).

**Comment by kilrau** [comment]
Opened 
- https://github.com/ExchangeUnion/xud/issues/1718
- https://github.com/ExchangeUnion/xud-docker/issues/586

as follow up for https://github.com/ExchangeUnion/market-maker-tools/issues/25#issuecomment-646963275

https://github.com/ExchangeUnion/market-maker-tools/issues/25#issue-642005069 missing tick is tracked in https://github.com/ExchangeUnion/market-maker-tools/issues/46.

Closing here.
